incorporate validation into gh actions

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -60,20 +60,48 @@ jobs:
 
       - uses: r-lib/actions/check-r-package@v1
 
-      - name: Simple buildModel execution
+      - name: Build and validate models
         run: |
           require(devtools)
           devtools::load_all()
-          run1 <- useeior::buildModel("USEEIOv2.0")
-          run2 <- useeior::buildModel("USEEIOv2.0.1")
-          run3 <- useeior::buildModel("USEEIOv2.1")
-          exists("run1"); exists("run2"); exists("run3")
+          for modelname in c("USEEIOv2.0", "USEEIOv2.0.01", "USEEIOv2.1"){
+          m <- useeior::buildModel(modelname)
+          
+          econval <- compareOutputandLeontiefXDemand(m, tolerance = 0.01)
+          paste("Number of sectors passing:",econval$N_Pass)
+          paste("Number of sectors failing:",econval$N_Fail)
+          paste("Sectors failing:", paste(econval$Failure$rownames, collapse = ", "))
+          
+          econval <- compareOutputandLeontiefXDemand(m,use_domestic=TRUE, tolerance = 0.01)
+          paste("Number of sectors passing:",econval$N_Pass)
+          paste("Number of sectors failing:",econval$N_Fail)
+          paste("Sectors failing:", paste(econval$Failure$rownames, collapse = ", "))
+          
+          modelval <- compareEandLCIResult(m, tolerance = 0.01)
+          paste("Number of flow totals by commodity passing:",modelval$N_Pass)
+          paste("Number of flow totals by commodity failing:",modelval$N_Fail)
+          
+          dom_val <- compareEandLCIResult(m, use_domestic=TRUE, tolerance = 0.01)
+          paste("Number of flow totals by commodity passing:",dom_val$N_Pass)
+          paste("Number of flow totals by commodity failing:",dom_val$N_Fail)
+          paste("Sectors with flow totals failing:", paste(dom_val$Failure$variable, collapse = ", "))  
+
+          q_x_val <- compareCommodityOutputXMarketShareandIndustryOutputwithCPITransformation(m, tolerance = 0.01)
+          paste("Number of flow totals by commodity passing:",q_x_val$N_Pass)
+          paste("Number of flow totals by commodity failing:",q_x_val$N_Fail)
+          paste("Sectors with flow totals failing:", paste(q_x_val$Failure$rownames, collapse = ", "))
+          
+          q_val <- compareCommodityOutputandDomesticUseplusProductionDemand(m, tolerance = 0.01)
+          paste("Number of flow totals by commodity passing:",q_val$N_Pass)
+          paste("Number of flow totals by commodity failing:",q_val$N_Fail)
+          paste("Sectors with flow totals failing:", paste(q_val$Failure$rownames, collapse = ", "))             
+          }
         shell: Rscript {0}
       
-      - name: Show testthat output
-        if: always()  # step will run even if previous steps fail
-        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
-        shell: bash
+      #- name: Show testthat output
+      #  if: always()  # step will run even if previous steps fail
+      #  run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
+      #  shell: bash
 
       - name: Upload check results
         if: failure()  # if any of the previous steps fail, export a log
